config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django.conf.urls.i18n import i18n_patterns
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = i18n_patterns(
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    path("", TemplateView.as_view(template_name='index.html'), name='home'),
    path("users/", include("main_service_of_plotters.apps.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    # Your stuff: custom urls includes go here
    path("tickets/", include("main_service_of_plotters.apps.ticket.urls", namespace="tickets")),
    path("statistics/", include("main_service_of_plotters.apps.statistics.urls", namespace="statistics")),

 ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# URLs without i18n
urlpatterns += [
    path("acra/", include("main_service_of_plotters.apps.acra.urls")),
    path("api/schema/", SpectacularAPIView.as_view(), name='schema'),
    path("api/schema/swagger-ui/", SpectacularSwaggerView.as_view(), name='swagger-ui'),
    path("api/schema/redoc/", SpectacularRedocView.as_view(), name='redoc'),
]

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    # path("auth-token/", obtain_auth_token),
    # JWT auth token
    path("api/token/", TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path("api/token/refresh/", TokenRefreshView.as_view(), name='token_refresh'),
    # FIXME api auth methods
    path('api-auth/', include(
        'rest_framework.urls',
        namespace='rest_framework'
    )),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

main_service_of_plotters/apps/ticket/urls.py
"""This module register url."""

from django.urls import path

from .views import (
    UserAddTicket,
    TicketListView,
    TicketDetailView,
    CloseTicketView,
    TechSpecTicketListView,
    PushTicketInWorkView,
    SolveTicketView,
)

app_name = "tickets"
urlpatterns = [
    path('report-problem/', UserAddTicket.as_view(), name='user_add_ticket'),
    path('', TicketListView.as_view(), name='ticket_list'),
    path('<int:pk>/', TicketDetailView.as_view(), name='ticket_detail'),
    path('<int:pk>/close/', CloseTicketView.as_view(), name='close_ticket'),
    path('solving-tickets/', TechSpecTicketListView.as_view(), name='tech_spec_list'),
    path('<int:pk>/push-in-work/', PushTicketInWorkView.as_view(), name='push_ticket_in_work'),
    path('<int:pk>/solve/', SolveTicketView.as_view(), name='solve_ticket')
]

main_service_of_plotters/apps/ticket/models.py
"""Models for work with tickets here."""

from django.db import models
from django.utils.translation import gettext_lazy as _

from main_service_of_plotters.utils.abstractmodel import DateTimeDateUpdate
from main_service_of_plotters.apps.users.models import User
from main_service_of_plotters.apps.users.constants import ROLE
from main_service_of_plotters.apps.device.models import Plotter
from .constants import StatusVariants, HEADER_MAX_LENGTH


class Ticket(DateTimeDateUpdate):
    """Request for a technical support with description of the problem."""

    status_variants = StatusVariants

    header = models.CharField(
        verbose_name=_("Header"),
        max_length=HEADER_MAX_LENGTH,
        blank=False,
        help_text=_("Short description of problem.")
    )
    text = models.TextField(
        verbose_name=_("Text"),
        help_text=_("Description of problem"),
        blank=True
    )
    media_file = models.FileField(
        verbose_name=_('Attached media file'),
        upload_to='ticket_media/',
        null=True,
        blank=True
    )
    status = models.CharField(
        verbose_name=_("Status"),
        max_length=1,
        blank=False,
        choices=StatusVariants.choices,
        default=StatusVariants.OPEN
    )
    reporter = models.ForeignKey(
        verbose_name=_("Reporter"),
        to=User,
        limit_choices_to={'role': ROLE["User"]},
        on_delete=models.CASCADE,
        related_name='created_tickets',
        help_text=_("User who create ticket"),
        null=False,
        blank=False
    )
    plotters = models.ManyToManyField(
        verbose_name=_("Plotters"),
        to=Plotter,
        related_name="tickets",
        blank=False
    )
    assignee = models.ForeignKey(
        verbose_name=_("Assignee"),
        to=User,
        limit_choices_to={'role': ROLE["Technical_Specialist"]},
        on_delete=models.SET_NULL,
        related_name='managed_tickets',
        null=True,
        blank=True,
        help_text=_('Technical Specialist who manage ticket')
    )
    answer = models.TextField(
        verbose_name=_("Answer"),
        blank=True,
        help_text=_("Answer of assigned technical specialist")
    )
    answer_attached_file = models.FileField(
        verbose_name=_('Answer media file'),
        upload_to='ticket_media/',
        null=True,
        blank=True,
        help_text=_("Media file attached by assigned technical specialist")
    )

    class Meta:
        """Metadata of Ticket."""

        verbose_name = _("Ticket")
        verbose_name_plural = _("Tickets")
        permissions = [
            ("can_report_problem", "Can report a problem"),
            ("can_close_ticket", "Can change ticket status to Close"),
            ("can_solve_problems", "Can solve ticket's problems"),
        ]

    def __str__(self):
        """Return string representation of ticket."""
        return f"{_('Ticket')} #{self.pk}: \"{self.header}\""


class PopularProblem(models.Model):
    """Model describe list with popular problems."""

    name = models.CharField(
        verbose_name=_("Name"),
        max_length=100,
        help_text=_("Short name of problem, will be displayed"),
        blank=False
    )
    populated_header = models.CharField(
        verbose_name=_("Populated Header"),
        max_length=HEADER_MAX_LENGTH,
        blank=False,
        help_text=_("Text what will be populated in created ticket header")
    )
    populated_text = models.TextField(
        verbose_name=_("Populated Text"),
        help_text=_("Text what will be populated in created ticket text"),
        blank=True
    )

    class Meta:
        """Metadata of Ticket."""

        verbose_name = _('Popular problem')
        verbose_name_plural = _('Popular problems')

    def __str__(self):
        """Return string representation of popular problem."""
        return f"{_('Popular problem')} \"{self.name}\""

main_service_of_plotters/apps/ticket/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.views import View
from django.views.generic import ListView, DetailView, RedirectView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseNotFound
from django.db.models import Q
from django.contrib import messages
from django.utils.translation import gettext as _
from django.http.response import HttpResponseForbidden

from .models import Ticket, PopularProblem
from .forms import (
    ChoosePopularProblemForm,
    VARIANT_NOT_PRESENTED,
    DetailedProblemFrom,
    SolveProblemForm
)
from .filters import TicketFilter


class TicketListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):

    permission_required = ('ticket.view_ticket',)

    def get_queryset(self):
        qs = Ticket.objects.all()
        if self.request.user.is_user():
            qs = qs.filter(reporter=self.request.user)
        elif self.request.user.is_technical_specialist():
            qs = qs.filter(
                Q(status=Ticket.status_variants.OPEN) |
                Q(assignee=self.request.user)
            )

        # filtering
        if filter_status := self.request.GET.get('filter_status', False):
            qs = qs.filter(status=filter_status)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["status_variants"] = Ticket.status_variants
        return context


class TicketDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):

    permission_required = ('ticket.view_ticket')
    queryset = Ticket.objects.all()


class UserAddTicket(LoginRequiredMixin, PermissionRequiredMixin, View):

    permission_required = ('ticket.can_report_problem',)

    _STEP_1_ACTION = 'step_1'
    _STEP_2_ACTION = 'step_2'

    def get(self, request):
        form = ChoosePopularProblemForm(context={'request': request})
        context = {
            'form': form,
            'action': self._STEP_1_ACTION
        }
        return render(
            request,
            template_name='ticket/add_ticket.html',
            context=context
        )

    def post(self, request):
        if self._is_popular_problem_choosed(request):
            condition = self._process_choosed_popular_problem(request)
        elif self._is_warriant_not_presented_choosed(request):
            condition = self._process_warriant_not_presented(request)
        elif self._is_detailed_problem_passed(request):
            condition = self._process_detailed_problem_passed(request)
        else:
            condition = HttpResponseNotFound()
        return condition

    def _is_popular_problem_choosed(self, request):
        return self._returned_after_page_with_popular_problem(request) \
            and request.POST.get('problem') != VARIANT_NOT_PRESENTED

    def _is_warriant_not_presented_choosed(self, request):
        return self._returned_after_page_with_popular_problem(request) \
            and request.POST.get('problem') == VARIANT_NOT_PRESENTED

    def _is_detailed_problem_passed(self, request):
        return self._returned_after_page_with_detailed_problem(request)

    def _returned_after_page_with_popular_problem(self, request):
        return request.POST.get('action') == self._STEP_1_ACTION

    def _returned_after_page_with_detailed_problem(self, request):
        return request.POST.get('action') == self._STEP_2_ACTION

    def _process_choosed_popular_problem(self, request):
        form = ChoosePopularProblemForm(request.POST)
        if form.is_valid():
            chosed_problem = get_object_or_404(
                PopularProblem,
                pk=form.cleaned_data['problem']
            )
            ticket = Ticket.objects.create(
                header=chosed_problem.populated_header,
                text=chosed_problem.populated_text,
                reporter=request.user
            )

            ticket.plotters.set(form.cleaned_data["plotters"])
            messages.add_message(request, messages.SUCCESS, f'{_("Your")} {ticket} {_("was sended to specialists!")}')

            return self._problem_posted_redirect()
        return None

    def _process_warriant_not_presented(self, request):
        prev_form = ChoosePopularProblemForm(request.POST)
        prev_form.is_valid()
        choosed_plotters = prev_form.cleaned_data['plotters']
        form = DetailedProblemFrom(
            context={'request': request},
            initial={'plotters': choosed_plotters})
        context = {
            'action': self._STEP_2_ACTION,
            'form': form}
        return render(request, 'ticket/add_ticket.html', context)

    def _process_detailed_problem_passed(self, request):
        form = DetailedProblemFrom(request.POST, request.FILES)
        print(form)
        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.reporter = request.user
            ticket.save()
            ticket.plotters.set(form.cleaned_data['plotters'])
            ticket.save()
            messages.add_message(request, messages.SUCCESS, f'{_("Your")} {ticket} {_("was sended to specialists!")}')
            return self._problem_posted_redirect()
        return HttpResponseNotFound()

    @staticmethod
    def _problem_posted_redirect():
        return redirect('tickets:ticket_list')


class CloseTicketView(LoginRequiredMixin, PermissionRequiredMixin, RedirectView):

    permission_required = ('ticket.can_close_ticket', )
    pattern_name = 'tickets:ticket_detail'

    def get_redirect_url(self, *args, **kwargs):
        ticket = get_object_or_404(Ticket, pk=kwargs['pk'])
        if ticket.reporter != self.request.user:
            return HttpResponseForbidden()
        ticket.status = ticket.status_variants.CLOSED
        ticket.save()
        messages.add_message(self.request, messages.SUCCESS, _("Ticket is closed"))
        return super().get_redirect_url(*args, **kwargs)


class TechSpecTicketListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):

    permission_required = ('ticket.can_solve_problems', )
    template_name = 'ticket/solving-tickets-list.html'
    queryset = Ticket.objects.all()

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(
                Q(status=Ticket.status_variants.OPEN) |
                Q(assignee=self.request.user)
            )
        self.filter = TicketFilter(self.request.GET, qs)
        print(self.filter.form)
        return self.filter.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter"] = self.filter
        return context



class SolveTicketView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):

    permission_required = ('ticket.can_solve_problems', )
    template_name = 'ticket/solve-ticket.html'
    model = Ticket
    fields = ['answer', 'answer_attached_file']

    def form_valid(self, form):
        self.object.status = Ticket.status_variants.SOLVED
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('tickets:solve_ticket', kwargs={'pk': self.object.pk})


class PushTicketInWorkView(LoginRequiredMixin, PermissionRequiredMixin, RedirectView):

    permission_required = ('ticket.can_solve_problems', )
    pattern_name = 'tickets:solve_ticket'

    def get_redirect_url(self, *args, **kwargs):
        ticket = get_object_or_404(Ticket, pk=kwargs['pk'])
        if ticket.status != Ticket.status_variants.OPEN:
            return HttpResponseNotFound
        ticket.assignee = self.request.user
        ticket.status = Ticket.status_variants.IN_WORK
        ticket.save()
        messages.add_message(
            self.request, messages.INFO,
            f'{_("You assigned to")} {ticket}. {_("Ticket status changed to")} {ticket.status}')
        return super().get_redirect_url(*args, **kwargs)

main_service_of_plotters/apps/ticket/templates/ticket/_status_badge.html
{% if ticket.status == 'O' %}
  <span class="badge badge-primary">
{% elif ticket.status == 'W'%}
  <span class="badge badge-warning">
{% elif ticket.status == 'S'%}
  <span class="badge badge-success">
{% else %}
  <span class="badge badge-secondary">
{% endif %}
{{ticket.get_status_display}}</span>

main_service_of_plotters/apps/ticket/templates/ticket/add_ticket.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form|crispy }}
    <input type="hidden" name="action" value="{{ action }}" />
    <input type="submit" name="apply" value='{% trans "Report" %}' />
</form>
{% endblock %}

main_service_of_plotters/apps/ticket/templates/ticket/admin_change_form.html
{% extends 'admin/change_form.html' %}
{% load i18n %}
{% load auth_extras %}
{% block submit_buttons_bottom %}
    {{ block.super }}
    {% if request.user|has_group:"User" %}
    <div class="submit-row">
            <input type="submit" value='{% trans "Close ticket" %}' name="_make_close">
    </div>
    {% elif request.user|has_group:"Technical_Specialist" %}
    <div class="submit-row">
            <input type="submit" value='{% trans "In Work" %}' name="_make_close">
    </div>
    {% endif %}
{% endblock %}

main_service_of_plotters/apps/ticket/templates/ticket/solve-ticket.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'tickets:ticket_list' %}">{% trans "Tickets" %}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'tickets:tech_spec_list' %}">{% trans "Solving problems" %}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ticket}}</li>
  </ol>
</nav>

  <h1>
    {% trans 'Ticket' %} #{{ ticket.id }}
    {% include 'ticket/_status_badge.html' %}
  </h1>
  <h2>{{ticket.header}}</h2>
  <ul>
    <li>{{ticket.text}}</li>
    <li>{% trans "Plotters" %}:
      <ul>{% for plotter in ticket.plotters.all %}
        <li>{{plotter}}</li>
      {% endfor %}</ul>
    {% if ticket.media_file %}
      <li><img src="{{ ticket.media_file.url }}" alt="attached media file"></li>
    {% endif %}
  <li>{% trans "Assignee" %}: {{ ticket.assignee }}<li>
  </ul>
  {% if ticket.status == 'O' %}
    <a href="{% url 'tickets:push_ticket_in_work' pk=ticket.pk %}"role="button" class="btn btn-warning">
      {% trans "Push in Work" %}
    </a>
  {% elif ticket.status == 'W' %}
  </ul>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
     {{ form|crispy }}
     <input type="submit" value="{% trans 'Solve' %}">
    </form>
  {% else %}
    <li>{% trans "Answer" %}: {{ticket.answer}}</li>
    {% if ticket.answer_attached_file %}
      <li><img src="{{ ticket.answer_attached_file.url }}" alt="answer attached media file"></li>
    {% endif %}
  </ul>
  {% endif %}
{% endblock content %}

main_service_of_plotters/apps/ticket/templates/ticket/solving-tickets-list.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'tickets:ticket_list' %}">{% trans "Tickets" %}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{% trans "Solving problems" %}</li>
  </ol>
</nav>

<ul>{% for ticket in ticket_list %}
  <li>
    {{ ticket }}
    {% include 'ticket/_status_badge.html' %}
    <a href="{% url 'tickets:solve_ticket' pk=ticket.pk %}" role="button" class="btn btn-primary">{% trans "Consider" %}</a>
  </li>
{% endfor %} </ul>

<form method="get">
  {{ filter.form|crispy }}
  <input type="submit" value="{% trans 'Filtering' %}" />
</form>

{% endblock %}

main_service_of_plotters/apps/ticket/templates/ticket/ticket_detail.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'tickets:ticket_list' %}">{% trans "Tickets" %}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ticket}}</li>
  </ol>
</nav>

  <h1>
    {% trans 'Ticket' %} #{{ ticket.id }}
    {% include 'ticket/_status_badge.html' %}
  </h1>
  <h2>{{ticket.header}}</h2>
  <ul>
    <li>{{ticket.text}}</li>
    <li>{% trans "Plotters" %}:
      <ul>{% for plotter in ticket.plotters.all %}
        <li>{{plotter}}</li>
      {% endfor %}</ul>
    {% if ticket.media_file %}
      <li><img src="{{ ticket.media_file.url }}" alt="attached media file"></li>
    {% endif %}
    {% if ticket.status == 'S' or ticket.status == 'C'%}
      <li>{% trans "Answer" %}: {{ticket.answer}}</li>
      {% if ticket.answer_attached_file %}
        <li><img src="{{ ticket.answer_attached_file.url }}" alt="answer attached media file"></li>
      {% endif %}
    {% endif %}
  </ul>
  {% if ticket.reporter == request.user and perms.ticket.can_close_ticket and ticket.status != 'C' %}
     <a href="{% url 'tickets:close_ticket' pk=ticket.pk %}" role="button" class="btn btn-primary">{% trans "Close the ticket" %}</a>
  {% endif %}
{% endblock content %}

main_service_of_plotters/apps/ticket/templates/ticket/ticket_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">{% trans "Tickets" %}</li>
  </ol>
</nav>

<ul>{% for ticket in ticket_list %}
  <li><a href="{% url 'tickets:ticket_detail' ticket.pk %}">
    {{ ticket }}<a>
    {% include 'ticket/_status_badge.html' %}
  </li>
{% endfor %} </ul>

{% if perms.ticket.can_report_problem %}
  <a href='{% url "tickets:user_add_ticket" %}'>{% trans "Report a problem" %}</a>
{% endif %}

<h2>{% trans "Filters" %}</h2>
<ul>
  {% for status in status_variants %}
    <li>
      <a href="{% url 'tickets:ticket_list' %}?filter_status={{ status }}">
        {{ status.label }}
      </a>
    </li>
  {% endfor %}
    <li>
      <a href="{% url 'tickets:ticket_list' %}">
        {% trans "All" %}
      </a>
    </li>
</ul>
{% if perms.ticket.can_solve_problems %}
    <a href="{% url 'tickets:tech_spec_list'%}" role="button" class="btn btn-warning">
      {% trans "Start to solve porblems" %}
    </a>
{% endif %}
{% endblock %}